### ISSUE TITLE
Prevent multiple show() calls from adding extra views

### ISSUE THREAD

**Issue by mbalex99** [pixyzehn/MediumProgressView#3]
When you call show()
It adds another view even if one is in place. Thus, hide() only removes one. 

Since the shared instance is tied to once instance of the view, hide() should remove all views and show should only add if none are presented.

**Comment by pixyzehn** [comment]
@mbalex99
Definitely. I'll fix that. Thank you for your comment.

**Comment by pixyzehn** [comment]
@mbalex99
Fixed. If you wanna know it, please look the below link.
https://github.com/pixyzehn/MediumProgressView/commit/2a5b6d55b9de4430dd67d9fe3cd891cadeb928a2#diff-f746614c5caaf49afedf89957a9c1004R41

**Comment by mbalex99** [comment]
Looks great. I just ran a loop through subviews for the type and removed them (if they exist) and added them!

**Comment by pixyzehn** [comment]
👍
